# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a684f70b7d7a130939f6ec0e1db0c58282908f5fbc42529ac24fd36b3c569f70f83dac82e90309159257861e4a041a54dbeca41b54cf9dcb45080606fe75a59d

test:
  secret_key_base: e6da8ed0f4d9ce71dd110d9390eb97d6ce957c84564bf1f8127578302e2c83bca56d92680d5267fe429a0b262e3c779471de63d9394bd254012080fad366a690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
