Question.create bottom: 'jeans', top: 'business'
Question.create bottom: 'jeans', top: 'business'
Question.create bottom: 'jeans', top: 'business'
Question.create bottom: 'jeans', top: 'business'
Question.create bottom: 'jeans', top: 'business'